# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            零度创新摄影工作室
tagline:          以学生为主体的摄影工作室
url:              https://naosunshang.github.io/
paginate:         1
baseurl:          /
author:
  name:           零度创新
  url:            https://naosunshang.github.io/
  email:          3088715648@qq.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
